# Generated by Django 2.2 on 2019-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devnotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devnote',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
