# Generated by Django 2.2 on 2019-10-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devnotes', '0002_devnote_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='devnote',
            name='name',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
